SKILLS = {
	acrobatics: {name: "Acrobatics", stat: "acrobatics", group: "Skills"},
	animalHandling: {name: "Animal Handling", stat: "animalHandling", group: "Skills"},
	arcana: {name: "Arcana", stat: "arcana", group: "Skills"},
	athletics: {name: "Athletics", stat: "athletics", group: "Skills"},
	deception: {name: "Deception", stat: "deception", group: "Skills"},
	history: {name: "History", stat: "history", group: "Skills"},
	insight: {name: "Insight", stat: "insight", group: "Skills"},
	intimidation: {name: "Intimidation", stat: "intimidation", group: "Skills"},
	investigation: {name: "Investigation", stat: "investigation", group: "Skills"},
	medicine: {name: "Medicine", stat: "medicine", group: "Skills"},
	nature: {name: "Nature", stat: "nature", group: "Skills"},
	perception: {name: "Perception", stat: "perception", group: "Skills"},
	performance: {name: "Performance", stat: "performance", group: "Skills"},
	persuasion: {name: "Persuasion", stat: "persuasion", group: "Skills"},
	religion: {name: "Religion", stat: "religion", group: "Skills"},
	sleightOfHand: {name: "Sleight of Hand", stat: "sleightOfHand", group: "Skills"},
	stealth: {name: "Stealth", stat: "stealth", group: "Skills"},
	survival: {name: "Survival", stat: "survival", group: "Skills"},
	initiative: {name: "Initiative", stat: "initiative", group: "Skills"},
};
